### ISSUE TITLE
I tried getting good, but I got got instead.

### ISSUE THREAD

**Issue by ryne-andal** [sammarks/ablecore#52]
See title.

**Comment by jeromehollon** [comment]
This is a serious issue. When will this be address by the developer?

**Comment by joshstrange** [comment]
+1, this is really slowing us down.

**Comment by sammarks** [comment]
Pull request?

**Comment by ryne-andal** [comment]
Is the developer still maintaining this code base?

**Comment by sammarks** [comment]
Yes, pull request?

**Comment by jeromehollon** [comment]
Bump.

**Comment by sammarks** [comment]
I find it very joshstrange that OP has not delivered on his pull request.

**Comment by joshstrange** [comment]
Just leaving a comment to subscribe

**Comment by jeromehollon** [comment]
I'm twelve, what is this?

**Comment by joshstrange** [comment]
Please replace all instances of "His/Her" with gender neutral terms

**Comment by jeromehollon** [comment]
This should be reopend. Issue is still occurring.

**Comment by joshstrange** [comment]
Same here, I can reproduce on the master branch
